# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cachirulo Valley
email: hola@cachirulovalley.com
description: > # this means to ignore newlines until "baseurl:"
  Somos un colectivo independiente de personas que, a título individual,
  organiza distintas iniciativas y actividades para fomentar
  el ecosistema emprendedor tecnológico en Aragón.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cachirulovalley.com" # the base hostname & protocol for your site
twitter_username: cachirulovalley
github_username:  cachirulovalley
disqus_name: cachirulovalley

# Build settings
markdown: kramdown


include: ['_pages']
